# NumPy and SciPy

NumPy and SciPy are two extremely useful packages available to you. NumPy has the `numpy.array`, an n-dimensional array with tons of built in support. SciPy has an extremely powerful linear algebra package, along with function optimization and root finding. Both numpy and SciPy will be critical components of your code for the computer projects.

## The NumPy array

The NumPy array is one of the most versatile and powerful data containers available to you. It is effectively a python list, but much faster and tons of back-end supporting functions. Lets take a look:

In [18]:
import numpy as np #common practice

In [19]:
#array of integers
my_ints = np.array([1,2,3,4,5])
print(my_ints)

my_floats = np.array([1.,2.,3.,4.,5.])
print(my_floats)

my_ints_to_floats = np.array([1,2,3,4,5], dtype = np.float64)
print(my_ints_to_floats)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


You can store more than a single dimension of values in a numpy array.

In [20]:
my_2darray = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
print(my_2darray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


With the basics of the `numpy.array` reviewed, lets take a look at some helpful functions NumPy offers! This is a non-comprehensive list of the available constructors, but the ones presented may be relevant to you!

In [21]:
a = np.zeros( (4,5) )  #4 rows and 5 columns all filled with zero

b = np.ones( (4,5) )  #4 rows and 5 columns all filled with zero

c = np.full( (4,5), 8 )  # 4 rows and 5 columns all filled with 8

d = np.zeros_like( b )  # takes an input array and creates a new one with the same shape filled with zeros

e = np.ones_like( a )  #^ but with ones

f = np.linspace(0, 10, 100)  #100 numbers between 0 and 10, evenly spaced (inclusive bounds)

g = np.arange(0, 10, 1)  #numbers starting aat zero increased by 1 until 10

h = np.logspace(0, 10, 10)  #numbers starting at 1e0 ending at 1e10, with even spacing

i = np.diag(g)  #creates a 2-d array with the diagonal equal to g

j = np.diag(i)  #creates a 1-d array from the diagonal of h

NumPy arrays support two extremely cool features: splicing / indexing and universal functions. 

### Splicing and Indexing

In [22]:
a = np.random.rand(4,4)  #creates a 4x4 array filled with random numbers

#numpy arrays are indexing by row then column

# to get the element in the first column and second row (1x0):
a[1,0], a[1][0]

# to get the first row 
a[0]

# to get the first column
a[:, 0]

# to get the first row, but only the first 3 elements
a[0,:3]

# to get the first column, but only the last 3 elements
a[-3:,0]

# to get the 'center' 4 elements
a[1:3,1:3]

array([[0.21848129, 0.52863863],
       [0.53858394, 0.17646006]])

As you can tell, numpy indexing and splicing is very powerful! But also, these splices can serve as 'lvalues' in equations and can be set!

In [23]:
a = np.random.rand(4,4)
print(a) 

a[0,:3] = 0  #setting the first row's first three elements to 0
print(a)

[[0.63582038 0.13093213 0.05931763 0.03082272]
 [0.76049452 0.10993292 0.89967431 0.75532312]
 [0.59308169 0.57426909 0.57093172 0.81210837]
 [0.52335741 0.34510167 0.85141177 0.25579568]]
[[0.         0.         0.         0.03082272]
 [0.76049452 0.10993292 0.89967431 0.75532312]
 [0.59308169 0.57426909 0.57093172 0.81210837]
 [0.52335741 0.34510167 0.85141177 0.25579568]]


Lets scale this up, and say that we want to change only the tridiagonal entries...

In [24]:
a = np.zeros((10,10))
print(a)
for i in range(1,9):
    a[i,i-1:i+2] = [5,5,5]
print('\n',a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 5. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 5. 5. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 5. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 5. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 5. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 5. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 5. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 5. 5.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Universal functions (ufuncs)

Finally, lets look into universal functions! ufuncs are actually defined by NumPy to be a certain set of functions they provide (and operator overloads), however we will use them to simply be any function that can operate on whole numpy arrays at a time!

In [25]:
a = np.zeros((3,3))
print(a)

a += 2  # adding 2 to the whole array
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


The above code allows for all built-in python operators not just add. Additionally, numpy has math functions that apply to the whole array as well!

In [26]:
print(a)

a = np.exp(a)  #raising e to the values in the matrix
print(a)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[7.3890561 7.3890561 7.3890561]
 [7.3890561 7.3890561 7.3890561]
 [7.3890561 7.3890561 7.3890561]]


This is allowed by all numpy math functions, and is actually significantly faster than doing a for-loop! This is due to numpy being a python wrapping of C++ functions. The final tidbit about numpy is numerical integration of __*predefined*__ arrays, i.e. an array of flux values... 

In [27]:
a = np.linspace(0,10,100)
b = np.exp(a)

np.trapezoid(y = b, x = a)  #takes the trapezoidal rule over provided x and y

np.float64(22044.18983764174)

## SciPy

Much like NumPy, SciPy is a very powerful package, but offers different amazing modules and functions. 

The two modules from SciPy most likely to be helpful for the computer projects are `scipy.linalg` and `scipy.optimize`, but that is not to say the other SciPy modules are not extremely powerful and useful. These other modules will not be presented here, but you should still know about them: `scipy.integrate` (numerical integration of user functions), `scipy.differentiate` (numerical derivatives of user provided functions, jacobians, hessians...), `scipy.interpolate` (interpolation of n-dimensional data), `scipy.special` (special functions like the __*Bessel*__, Legendre, Sph, Zern...), `scipy.stats` (statistics package with various distribution types and predictors), `scipy.sparse` (sparse matrix linear algebra).

### SciPy Linear Algebra (non-sparse)

In [37]:
import scipy.linalg as sla

A = np.random.rand(5,5)
b = np.random.rand(5)

x = sla.solve(A, b)  #solve the system, faster than numpy.linalg.solve

vals, vecs = sla.eig(A)  #get the eigenvals and vectors of A, Sanity check your work!

SciPy linalg has a lot more functionality than just the above presented, but a lot of it is outside of the scope of this class. That said, if you ever need to solve any form of a matrix system you should use scipy!

### SciPy Optimize

Assuming no one wants to write their own root-finding algorithm (however cool and fun they are), `scipy.optimize` does it for you! 

A root finding function allows you to solve transcendental equations like so many of those criticality conditions...

In [47]:
import scipy.optimize as opt

def func(x):
    #say our equation is x+1 = exp(x)
    #All a root finding algorithm does is solve for when a function is 0
    # and so solve the system so one side is zero and voilla!
    return x+1 - np.exp(x)  

solution = opt.root(func, x0=[1])

#to extract the solution:
print(solution.x )

[-5.12986763e-09]


You should notice the final answer is not correct, as we expect 0. This is due to computational error, and is effectively negligible with respect to this class. 